### PR TITLE
fixed  score bud score bug this closes #66

### LINKED ISSUE #66: Score not updating

### PR DESCRIPTION
**Pull request by janamano**

### CODE REVIEW

File: src/components/Game.js [hunk 1]
```diff
@@ -93,6 +96,13 @@ export class Game extends Component {
 
   onEvent = (e) => {
     if (e.type === "game-over") {
+      this.setState({
+        lastScore: this.state.score
+      });
+      let highScoreBeat = setHighScore(this.state.score);
+      if (highScoreBeat) {
```
Comment (aniprasad) [inline src/components/Game.js:103]: Just add a comment here detailing why we have a check before we store
